### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by dlebrero** [konukhov/kfk-avro-bridge#2]
Would you be so kind of creating a non-snapshot version of the library? 

Thanks a lot,

Dan

**Comment by kfyodor** [comment]
Hey Dan,

I'm really sorry, I haven't seen any notifications about your issue and PR – just noticed it. I'll check it out ASAP if it's still needed.

Theodore.

**Comment by dlebrero** [comment]
Hi Theodore,

We don't need this anymore. We forked and created our own releases and we are publishing them to clojars. 

I just realised that we have an open pull requests that happens to have all of the changes that we made. Maybe you want to cherry pick some of the changes.

Cheers and thanks a lot!

Dan
